added automatic dotfiles updating on zsh launch (untested)

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -128,6 +128,50 @@ fi
 # wsl can't --cd into different directories on start through Windows Terminal wtf?
 export TRANSPARENCY=true
 
+
 ## Ranger
 # Ranger needs to be told to not overwrite configs?
 export RANGER_LOAD_DEFAULT_RC=false
+
+
+
+# =============================================================================
+#                               Update .dotfiles
+# =============================================================================
+# Check to make sure we are on the master branch
+if [[ ! -d ~/.dotfiles ]] then
+    exit 1
+end
+
+cd ~/.dotfiles
+CURRENTBRANCH=$(git status|awk 'NR==1{print $3}');
+
+# only update if on master branch
+if [ "$CURRENTBRANCH" == "master" ]; then
+    # Not on master - don't proceed
+    # Check whether the current working branch is ahead, behind or diverged from remote master, and exit if we're not using the current remote master
+    LOCAL=$(git rev-parse @)
+    REMOTE=$(git rev-parse @{u})
+    BASE=$(git merge-base @ @{u})
+
+    if [ "$LOCAL"=="$REMOTE" ]; then
+        # Up to date, do nothing.
+    elif [ "$LOCAL"=="$BASE" ]; then
+        # Behind, ask to auto update.
+        echo -e "There is an update available for your dotfiles;\n"
+        read -p "Do you want to update? [y]es/[N]o" -n 1 -r
+        if [[ $REPLY =~ ^[Yy]$ ]] then
+            echo -e "\n\nUpdating dotfiles...\n"
+            git pull --force
+            sh ~/.dotfiles/install
+            exec zsh
+        fi
+    elif [ "$REMOTE"=="$BASE" ]; then
+        #echo -e "Your working branch is ahead of the remote branch, you need to run:\ngit push origin master"
+        #exit 1
+    else
+        #echo "Your working branch has diverged from the remote master, cannot continue"
+        #exit 1
+    fi
+fi
+
